sudo: false
language: c
compiler:
  - gcc
env:
  - PROF="3.15"
  - PROF="3.14"
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
script: sh build-travis.sh
cache:
  directories:
  - $HOME/.cache
