sudo: false
language: c
compiler:
  - gcc
env:
  - BASE="R3.16.1"
  - BASE="R3.15.5"
  - BASE="R3.14.12.5"
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
install: sh build-travis.sh
script:  make -C code-listings
cache:
  directories:
  - $HOME/.cache
